2024-01-19 09:56:23 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup?go=demo
2024-01-19 09:56:23 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563003d54f83 <unknown>
#1 0x563003a0dcf7 <unknown>
#2 0x563003a5d99e <unknown>
#3 0x563003a5daa1 <unknown>
#4 0x563003aa8d64 <unknown>
#5 0x563003a870dd <unknown>
#6 0x563003aa6006 <unknown>
#7 0x563003a86e53 <unknown>
#8 0x563003a4edd4 <unknown>
#9 0x563003a501de <unknown>
#10 0x563003d19531 <unknown>
#11 0x563003d1d455 <unknown>
#12 0x563003d05f55 <unknown>
#13 0x563003d1e0ef <unknown>
#14 0x563003ce999f <unknown>
#15 0x563003d42008 <unknown>
#16 0x563003d421d7 <unknown>
#17 0x563003d54124 <unknown>
#18 0x7f81b2e94ac3 <unknown>

2024-01-19 09:56:30 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup?go=demo
2024-01-19 09:56:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563003d54f83 <unknown>
#1 0x563003a0dcf7 <unknown>
#2 0x563003a5d99e <unknown>
#3 0x563003a5daa1 <unknown>
#4 0x563003aa8d64 <unknown>
#5 0x563003a870dd <unknown>
#6 0x563003aa6006 <unknown>
#7 0x563003a86e53 <unknown>
#8 0x563003a4edd4 <unknown>
#9 0x563003a501de <unknown>
#10 0x563003d19531 <unknown>
#11 0x563003d1d455 <unknown>
#12 0x563003d05f55 <unknown>
#13 0x563003d1e0ef <unknown>
#14 0x563003ce999f <unknown>
#15 0x563003d42008 <unknown>
#16 0x563003d421d7 <unknown>
#17 0x563003d54124 <unknown>
#18 0x7f81b2e94ac3 <unknown>