2024-01-30 05:12:35 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/trade-gbpusd
2024-01-30 05:12:35 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559743120f83 <unknown>
#1 0x559742dd9cf7 <unknown>
#2 0x559742e2999e <unknown>
#3 0x559742e29aa1 <unknown>
#4 0x559742e74d64 <unknown>
#5 0x559742e530dd <unknown>
#6 0x559742e72006 <unknown>
#7 0x559742e52e53 <unknown>
#8 0x559742e1add4 <unknown>
#9 0x559742e1c1de <unknown>
#10 0x5597430e5531 <unknown>
#11 0x5597430e9455 <unknown>
#12 0x5597430d1f55 <unknown>
#13 0x5597430ea0ef <unknown>
#14 0x5597430b599f <unknown>
#15 0x55974310e008 <unknown>
#16 0x55974310e1d7 <unknown>
#17 0x559743120124 <unknown>
#18 0x7fb707894ac3 <unknown>

2024-01-30 05:12:38 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/trade-gbpusd
2024-01-30 05:12:38 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559743120f83 <unknown>
#1 0x559742dd9cf7 <unknown>
#2 0x559742e2999e <unknown>
#3 0x559742e29aa1 <unknown>
#4 0x559742e74d64 <unknown>
#5 0x559742e530dd <unknown>
#6 0x559742e72006 <unknown>
#7 0x559742e52e53 <unknown>
#8 0x559742e1add4 <unknown>
#9 0x559742e1c1de <unknown>
#10 0x5597430e5531 <unknown>
#11 0x5597430e9455 <unknown>
#12 0x5597430d1f55 <unknown>
#13 0x5597430ea0ef <unknown>
#14 0x5597430b599f <unknown>
#15 0x55974310e008 <unknown>
#16 0x55974310e1d7 <unknown>
#17 0x559743120124 <unknown>
#18 0x7fb707894ac3 <unknown>